CREATE TABLE Customers (
    id INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    FirstName VARCHAR(32) NOT NULL,
    LastName VARCHAR(32) NOT NULL,
    username VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(32) NOT NULL
);


CREATE TABLE Transactions (
    id INT(6) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
    customerId INT NOT NULL REFERENCES Customers(id),
    imageId INT NOT NULL REFERENCES Images(id),
    date TIMESTAMP NOT NULL
);